# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import innerProto.inner_pb2 as inner__pb2


class eVotingReplicaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ElectionReplica = channel.unary_unary(
                '/innervoting.eVotingReplica/ElectionReplica',
                request_serializer=inner__pb2.Election.SerializeToString,
                response_deserializer=inner__pb2.Status.FromString,
                )
        self.CastVoteReplica = channel.unary_unary(
                '/innervoting.eVotingReplica/CastVoteReplica',
                request_serializer=inner__pb2.Vote.SerializeToString,
                response_deserializer=inner__pb2.Status.FromString,
                )


class eVotingReplicaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ElectionReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CastVoteReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_eVotingReplicaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ElectionReplica': grpc.unary_unary_rpc_method_handler(
                    servicer.ElectionReplica,
                    request_deserializer=inner__pb2.Election.FromString,
                    response_serializer=inner__pb2.Status.SerializeToString,
            ),
            'CastVoteReplica': grpc.unary_unary_rpc_method_handler(
                    servicer.CastVoteReplica,
                    request_deserializer=inner__pb2.Vote.FromString,
                    response_serializer=inner__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'innervoting.eVotingReplica', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class eVotingReplica(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ElectionReplica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/innervoting.eVotingReplica/ElectionReplica',
            inner__pb2.Election.SerializeToString,
            inner__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CastVoteReplica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/innervoting.eVotingReplica/CastVoteReplica',
            inner__pb2.Vote.SerializeToString,
            inner__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
