# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inner.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0binner.proto\x12\x0binnervoting\x1a\x1fgoogle/protobuf/timestamp.proto\"$\n\x05Voter\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05group\x18\x02 \x02(\t\"\x16\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x02(\x05\"g\n\x08\x45lection\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0e\n\x06groups\x18\x02 \x03(\t\x12\x0f\n\x07\x63hoices\x18\x03 \x03(\t\x12,\n\x08\x65nd_date\x18\x04 \x02(\x0b\x32\x1a.google.protobuf.Timestamp\"2\n\x04Vote\x12\x15\n\relection_name\x18\x01 \x02(\t\x12\x13\n\x0b\x63hoice_name\x18\x02 \x02(\t\"/\n\tVoteCount\x12\x13\n\x0b\x63hoice_name\x18\x01 \x02(\t\x12\r\n\x05\x63ount\x18\x02 \x02(\x05\"\xa4\x01\n\x0e\x45lectionStatus\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0e\n\x06groups\x18\x02 \x03(\t\x12\x0f\n\x07\x63hoices\x18\x03 \x03(\t\x12%\n\x05\x63ount\x18\x04 \x03(\x0b\x32\x16.innervoting.VoteCount\x12\x0e\n\x06voters\x18\x05 \x03(\t\x12,\n\x08\x65nd_date\x18\x06 \x02(\x0b\x32\x1a.google.protobuf.Timestamp2\x8a\x01\n\x0e\x65VotingReplica\x12=\n\x0f\x45lectionReplica\x12\x15.innervoting.Election\x1a\x13.innervoting.Status\x12\x39\n\x0f\x43\x61stVoteReplica\x12\x11.innervoting.Vote\x1a\x13.innervoting.Status')



_VOTER = DESCRIPTOR.message_types_by_name['Voter']
_STATUS = DESCRIPTOR.message_types_by_name['Status']
_ELECTION = DESCRIPTOR.message_types_by_name['Election']
_VOTE = DESCRIPTOR.message_types_by_name['Vote']
_VOTECOUNT = DESCRIPTOR.message_types_by_name['VoteCount']
_ELECTIONSTATUS = DESCRIPTOR.message_types_by_name['ElectionStatus']
Voter = _reflection.GeneratedProtocolMessageType('Voter', (_message.Message,), {
  'DESCRIPTOR' : _VOTER,
  '__module__' : 'inner_pb2'
  # @@protoc_insertion_point(class_scope:innervoting.Voter)
  })
_sym_db.RegisterMessage(Voter)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'inner_pb2'
  # @@protoc_insertion_point(class_scope:innervoting.Status)
  })
_sym_db.RegisterMessage(Status)

Election = _reflection.GeneratedProtocolMessageType('Election', (_message.Message,), {
  'DESCRIPTOR' : _ELECTION,
  '__module__' : 'inner_pb2'
  # @@protoc_insertion_point(class_scope:innervoting.Election)
  })
_sym_db.RegisterMessage(Election)

Vote = _reflection.GeneratedProtocolMessageType('Vote', (_message.Message,), {
  'DESCRIPTOR' : _VOTE,
  '__module__' : 'inner_pb2'
  # @@protoc_insertion_point(class_scope:innervoting.Vote)
  })
_sym_db.RegisterMessage(Vote)

VoteCount = _reflection.GeneratedProtocolMessageType('VoteCount', (_message.Message,), {
  'DESCRIPTOR' : _VOTECOUNT,
  '__module__' : 'inner_pb2'
  # @@protoc_insertion_point(class_scope:innervoting.VoteCount)
  })
_sym_db.RegisterMessage(VoteCount)

ElectionStatus = _reflection.GeneratedProtocolMessageType('ElectionStatus', (_message.Message,), {
  'DESCRIPTOR' : _ELECTIONSTATUS,
  '__module__' : 'inner_pb2'
  # @@protoc_insertion_point(class_scope:innervoting.ElectionStatus)
  })
_sym_db.RegisterMessage(ElectionStatus)

_EVOTINGREPLICA = DESCRIPTOR.services_by_name['eVotingReplica']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOTER._serialized_start=61
  _VOTER._serialized_end=97
  _STATUS._serialized_start=99
  _STATUS._serialized_end=121
  _ELECTION._serialized_start=123
  _ELECTION._serialized_end=226
  _VOTE._serialized_start=228
  _VOTE._serialized_end=278
  _VOTECOUNT._serialized_start=280
  _VOTECOUNT._serialized_end=327
  _ELECTIONSTATUS._serialized_start=330
  _ELECTIONSTATUS._serialized_end=494
  _EVOTINGREPLICA._serialized_start=497
  _EVOTINGREPLICA._serialized_end=635
# @@protoc_insertion_point(module_scope)
